package(features=["warning_compile_flags"])

cc_test(
    name = "sqlitecpp_test",
    srcs = ["sqlitecpp_test.cc"],
    deps = [
        "@sqlitecpp",
        "@com_google_googletest//:gtest_main"
    ]
)