# Example machine configuration for Lambda Cloud training jobs
# Copy and modify this file for your specific setup

# Lambda Cloud instance types to try (in order of preference)
machine_types:
  - gpu_1x_gh200 # Preferred GPU type

# Region(s) to launch instances in (single region or list of regions)
region: us-east-3

# SSH key name registered with Lambda Cloud
ssh_key: aspen

# Image family to use for instances
image_family: lambda-stack-24-04

# File systems to mount (default: vigor dataset)
file_systems:
  - vigor

# Files to copy from local machine to remote instance
files_to_copy:
  # Copy torch model cache (adjust path as needed)
  ~/.cache/torch/hub/checkpoints: /home/ubuntu/.cache/torch/hub/checkpoints
  ~/.aws/credentials: ~/.aws/credentials
  
  # Copy tmux configuration
  ~/.tmux.conf: ~/.tmux.conf

# Commands to run on the remote instance during setup
# Note: Repository cloning and setup.sh are handled automatically
remote_setup_commands:
  # Datasets are automatically mounted from vigor filesystem
  # Copy datasets to /tmp/ for faster access during training
  - cp -r vigor/Chicago /tmp/
  - cp -r vigor/Seattle /tmp/
  
  # Create output directory
  - mkdir -p /tmp/output

# Maximum training time in hours (jobs will be terminated after this time)
max_train_time_hours: 6