[experimental]

[display]
dataframes = "rich"
theme = "light"
default_width = "medium"
cell_output = "below"
code_editor_font_size = 14

[formatting]
line_length = 79

[completion]
copilot = false
activate_on_typing = true

[snippets]
include_default_snippets = true
custom_paths = []

[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = false

[server]
browser = "default"
follow_symlink = true

[keymap]
preset = "vim"
[keymap.overrides]

[package_management]
manager = "pip"

[ai]
rules = ""

[runtime]
auto_reload = "autorun"
std_stream_max_bytes = 1000000
watcher_on_save = "lazy"
auto_instantiate = true
output_max_bytes = 8000000
on_cell_change = "autorun"
