[completion]
copilot = false
activate_on_typing = true

[runtime]
std_stream_max_bytes = 1000000
watcher_on_save = "lazy"
auto_instantiate = false
on_cell_change = "autorun"
output_max_bytes = 8000000
auto_reload = "off"

[experimental]

[package_management]
manager = "pip"

[save]
autosave_delay = 1000
format_on_save = false
autosave = "after_delay"

[formatting]
line_length = 79

[display]
code_editor_font_size = 14
cell_output = "below"
default_width = "full"
dataframes = "rich"
theme = "light"

[server]
browser = "default"
follow_symlink = true

[snippets]
include_default_snippets = true
custom_paths = []

[ai]
rules = ""

[keymap]
preset = "default"
[keymap.overrides]
