
package(features=["warning_compile_flags"])

cc_library(
  name = "gl_window",
  hdrs = ["gl_window.hh"],
  srcs = ["gl_window.cc"],
  deps = ["@glfw//:glfw"],
  visibility = ["//visibility:public"],
)
