"""Index-page generators: make a data-root snapshot clickable.

`refresh(data_root)` regenerates the navigation chain by scanning the disk —
no hand-maintained HTML and no hardcoded dataset lists:

  <root>/index.html                     lanes with counts
  <root>/datasets/index.html            dataset table (+ per-dataset assets)
  <root>/artifacts/index.html           artifact kinds
  <root>/artifacts/<kind>/index.html    dataset -> versions (manifest info)
  <root>/runs/index.html                experiment table
  <root>/runs/<experiment>/index.html   experiment.md rendered + run table

Stage-produced pages in artifact or diagnostic directories are linked, never
regenerated, from here. Every page this module owns starts with
INDEX_GENERATED_MARK. refresh() refuses to overwrite any index.html without
that exact ownership header, including pages carrying the generic viewer
marker, so a stage-owned or hand-made page is never clobbered.

Each page replacement is atomic, and concurrent refreshes are serialized.
Canonical direct publications invoke this helper after their artifact is
validated.  The refresh_indexes target remains available to repair or
manually refresh a navigation snapshot.
"""

from contextlib import contextmanager
import fcntl
import json
import os
from pathlib import Path
import stat

from experimental.overhead_matching.swag.farfield import artifact as artifact_lib
from experimental.overhead_matching.swag.farfield.viewers import page as pg

GENERATOR = "farfield.viewers.indexes"
INDEX_GENERATED_MARK = "<!-- generated by farfield.viewers.indexes -->"
LOCK_NAME = ".farfield-indexes.lock"


class IndexRefreshError(RuntimeError):
    """The requested tree cannot be scanned or safely published."""


# Files worth surfacing on a dataset row when present.
DATASET_ASSETS = ("trajectory.png", "vehicle_anchor.png",
                  "gps_timelapse.mp4")

# (directory suffix, page path, label), in display order. These paths are
# relative to an experiment index beside the run and its diagnostic siblings.
RUN_SIBLING_PAGES = (
    (".viewer", "viewer.html", "filter viewer"),
    (".plots", "map.png", "map"),
)

# Directories with these reserved suffixes are derived diagnostics or partial
# publications, not completed localization runs. Keep them out of run counts
# and rows even when the experiment directory contains no typed metadata.
RUN_SIDE_DIRECTORY_SUFFIXES = (
    ".viewer",
    ".plots",
    ".satellite",
    ".counterfactuals",
    ".attribution",
    artifact_lib.INCOMPLETE_SUFFIX,
)


def _require_directory(path: Path, *, allow_missing: bool = False) -> bool:
    """Validate one directory without following a final symlink."""
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        if allow_missing:
            return False
        raise IndexRefreshError(f"directory does not exist: {path}") from None
    if stat.S_ISLNK(metadata.st_mode):
        raise IndexRefreshError(f"refusing symlink directory: {path}")
    if not stat.S_ISDIR(metadata.st_mode):
        raise IndexRefreshError(
            f"expected directory, found another entry: {path}")
    return True


@contextmanager
def _exclusive_refresh_lock(data_root: Path):
    """Hold the persistent, root-local lock for one complete refresh."""
    lock_path = data_root / LOCK_NAME
    flags = os.O_RDWR | os.O_CREAT
    flags |= getattr(os, "O_CLOEXEC", 0)
    flags |= getattr(os, "O_NOFOLLOW", 0)
    flags |= getattr(os, "O_NONBLOCK", 0)
    try:
        descriptor = os.open(lock_path, flags, 0o600)
    except OSError as exc:
        raise IndexRefreshError(
            f"cannot open refresh lock as a regular file: {lock_path}") from exc
    try:
        if not stat.S_ISREG(os.fstat(descriptor).st_mode):
            raise IndexRefreshError(
                f"refresh lock is not a regular file: {lock_path}")
        fcntl.flock(descriptor, fcntl.LOCK_EX)
        yield
    finally:
        try:
            fcntl.flock(descriptor, fcntl.LOCK_UN)
        finally:
            os.close(descriptor)


def _write_index(directory: Path, html: str, skipped: list[str]) -> None:
    _require_directory(directory)
    target = Path(directory) / "index.html"
    try:
        target_metadata = target.lstat()
    except FileNotFoundError:
        pass
    else:
        if stat.S_ISLNK(target_metadata.st_mode):
            skipped.append(str(target))
            return
        if not stat.S_ISREG(target_metadata.st_mode):
            raise IndexRefreshError(
                f"index target is not a regular file: {target}")
        with target.open(errors="replace") as stream:
            ownership_header = stream.readline(256).rstrip("\r\n")
        if ownership_header != INDEX_GENERATED_MARK:
            skipped.append(str(target))
            return
    artifact_lib.atomic_write_file(target, html.encode("utf-8"))


def _manifest_summary(version_dir: Path) -> tuple:
    manifest = version_dir / "manifest.json"
    if not manifest.exists():
        return ("<span class='warn'>no manifest</span>", "")
    try:
        doc = json.loads(manifest.read_text())
    except json.JSONDecodeError:
        return ("<span class='bad'>unreadable manifest</span>", "")
    return (pg.esc(doc.get("generator", "?")),
            pg.esc(doc.get("created", "")))


def _dirs(path: Path) -> list[Path]:
    if not _require_directory(path, allow_missing=True):
        return []
    directories = []
    for entry in path.iterdir():
        if entry.name.startswith("."):
            continue
        if entry.is_symlink() and entry.is_dir():
            raise IndexRefreshError(f"refusing symlink directory: {entry}")
        if entry.is_dir():
            directories.append(entry)
    return sorted(directories, key=lambda entry: entry.name)


def _run_dirs(experiment: Path) -> list[Path]:
    """Return completed run candidates, excluding sibling diagnostics."""
    return [
        path for path in _dirs(experiment)
        if not path.name.endswith(RUN_SIDE_DIRECTORY_SUFFIXES)
    ]


def _regular_page(path: Path) -> bool:
    """Return whether one page exists, rejecting unsafe filesystem entries."""
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        return False
    if stat.S_ISLNK(metadata.st_mode):
        raise IndexRefreshError(f"refusing symlink page: {path}")
    if not stat.S_ISREG(metadata.st_mode):
        raise IndexRefreshError(f"page is not a regular file: {path}")
    return True


def _run_page_links(run: Path) -> list[tuple[str, str]]:
    """Resolve sibling pages without probing the immutable run directory."""
    links = []
    for suffix, relative, label in RUN_SIBLING_PAGES:
        directory = run.with_name(run.name + suffix)
        if not _require_directory(directory, allow_missing=True):
            continue
        if _regular_page(directory / relative):
            links.append((f"{directory.name}/{relative}", label))
    return links


def refresh(data_root: Path) -> dict:
    """Regenerate a snapshot under one lock, replacing each page atomically.

    Returns {"written": [...], "skipped": [...]} where skipped lists
    index.html files owned by something else.
    """
    data_root = Path(data_root)
    _require_directory(data_root)
    with _exclusive_refresh_lock(data_root):
        return _refresh_locked(data_root)


def _refresh_locked(data_root: Path) -> dict:
    written, skipped = [], []

    def emit(directory, title, body, crumbs):
        html = (f"{INDEX_GENERATED_MARK}\n" +
                pg.page(title, body, generator=GENERATOR, crumbs=crumbs))
        before = len(skipped)
        _write_index(directory, html, skipped)
        if len(skipped) == before:
            written.append(str(Path(directory) / "index.html"))

    # --- datasets lane -----------------------------------------------------
    datasets = _dirs(data_root / "datasets")
    rows = []
    for ds in datasets:
        assets = " ".join(
            f'<a href="{ds.name}/{name}">{name.split(".")[0]}</a>'
            for name in DATASET_ASSETS if (ds / name).exists())
        panorama_dir = ds / "panorama"
        n_panos = (len(list(panorama_dir.glob("*.jpg")))
                   if _require_directory(panorama_dir, allow_missing=True)
                   else 0)
        rows.append([f'<a href="{ds.name}/">{pg.esc(ds.name)}</a>',
                     str(n_panos), assets or "<span class='muted'>—</span>"])
    if _require_directory(data_root / "datasets", allow_missing=True):
        emit(data_root / "datasets", "datasets",
             pg.table(["dataset", "panoramas", "assets"], rows),
             [("farfield", "../index.html"), ("datasets", None)])

    # --- artifacts lane ----------------------------------------------------
    kinds = _dirs(data_root / "artifacts")
    for kind in kinds:
        krows = []
        for ds in _dirs(kind):
            versions = _dirs(ds)
            cells = []
            for version in versions:
                generator, created = _manifest_summary(version)
                inner = (f'<a href="{ds.name}/{version.name}/">'
                         f'{pg.esc(version.name)}</a>')
                # Link a version's own index page when a stage produced one.
                if (version / "index.html").exists():
                    inner = (f'<a href="{ds.name}/{version.name}/'
                             f'index.html">{pg.esc(version.name)}</a>')
                cells.append(f"{inner} <span class='muted'>{generator} "
                             f"{created}</span>")
            loose = [p.name for p in ds.iterdir()
                     if p.is_file() and p.suffix in (".feather", ".json")]
            for name in sorted(loose):
                cells.append(f'<a href="{ds.name}/{name}">{pg.esc(name)}</a>')
            krows.append([f"{pg.esc(ds.name)}", "<br>".join(cells)])
        emit(kind, f"artifacts / {kind.name}",
             pg.table(["dataset", "versions"], krows),
             [("farfield", "../../index.html"),
              ("artifacts", "../index.html"), (kind.name, None)])
    if _require_directory(data_root / "artifacts", allow_missing=True):
        emit(data_root / "artifacts", "artifacts",
             pg.table(["kind", "datasets"], [
                 [f'<a href="{k.name}/index.html">{pg.esc(k.name)}</a>',
                  str(len(_dirs(k)))] for k in kinds]),
             [("farfield", "../index.html"), ("artifacts", None)])

    # --- runs lane (experiments) --------------------------------------------
    experiments = _dirs(data_root / "runs")
    for experiment in experiments:
        body_parts = []
        notes = experiment / "experiment.md"
        if notes.exists():
            body_parts.append(pg.render_markdown_lite(notes.read_text()))
        else:
            body_parts.append(
                "<p class='warn'>no experiment.md — every experiment "
                "directory carries one (what is being explored, status, "
                "conclusions).</p>")
        run_rows = []
        for run in _run_dirs(experiment):
            links = " · ".join(
                f'<a href="{relative}">{label}</a>'
                for relative, label in _run_page_links(run))
            run_rows.append([pg.esc(run.name),
                             links or "<span class='muted'>no pages</span>"])
        body_parts.append(pg.table(["run", "pages"], run_rows))
        emit(experiment, experiment.name, "\n".join(body_parts),
             [("farfield", "../../index.html"), ("runs", "../index.html"),
              (experiment.name, None)])
    if _require_directory(data_root / "runs", allow_missing=True):
        rows = []
        for experiment in experiments:
            first_line = ""
            notes = experiment / "experiment.md"
            if notes.exists():
                for line in notes.read_text().splitlines():
                    if line.strip() and not line.startswith("#"):
                        first_line = line.strip()
                        break
            rows.append([
                f'<a href="{experiment.name}/index.html">'
                f'{pg.esc(experiment.name)}</a>',
                str(len(_run_dirs(experiment))), pg.esc(first_line)])
        emit(data_root / "runs", "runs (experiments)",
             pg.table(["experiment", "runs", "summary"], rows),
             [("farfield", "../index.html"), ("runs", None)])

    # --- root ----------------------------------------------------------------
    lane_rows = []
    for lane, blurb in (("datasets", "frozen problem definitions"),
                        ("artifacts", "derived per-dataset products"),
                        ("runs", "experiments (localization runs)"),
                        ("models", "weights"),
                        ("raw_material", "source material")):
        path = data_root / lane
        if not _require_directory(path, allow_missing=True):
            continue
        href = (f"{lane}/index.html"
                if (path / "index.html").exists()
                or lane in ("datasets", "artifacts", "runs") else f"{lane}/")
        lane_rows.append([f'<a href="{href}">{pg.esc(lane)}</a>',
                          str(len(_dirs(path))), pg.esc(blurb)])
    emit(data_root, "farfield data root",
         pg.table(["lane", "entries", ""], lane_rows),
         None)

    return {"written": written, "skipped": skipped}
