"""Index-page generators: make a data-root snapshot clickable.

`refresh(data_root)` regenerates the navigation chain by scanning the disk —
no hand-maintained HTML and no hardcoded dataset lists:

  <root>/index.html                     lanes with counts
  <root>/datasets/index.html            dataset table (+ per-dataset assets)
  <root>/artifacts/index.html           artifact kinds
  <root>/artifacts/<kind>/index.html    dataset -> versions (manifest info)
  <root>/runs/index.html                experiment table
  <root>/runs/<experiment>/index.html   experiment.md rendered + run table

Stage-produced pages in artifact or diagnostic directories are linked, never
regenerated, from here. Every page this module owns starts with
INDEX_GENERATED_MARK. refresh() refuses to overwrite any index.html without
that exact ownership header, including pages carrying the generic viewer
marker, so a stage-owned or hand-made page is never clobbered.

Each page replacement is atomic, and concurrent refreshes are serialized.
Canonical direct publications invoke this helper after their artifact is
validated.  The refresh_indexes target remains available to repair or
manually refresh a navigation snapshot.
"""

from contextlib import contextmanager
import fcntl
import json
import os
from pathlib import Path
import stat

from experimental.overhead_matching.swag.farfield import artifact as artifact_lib
from experimental.overhead_matching.swag.farfield.viewers import page as pg

GENERATOR = "farfield.viewers.indexes"
INDEX_GENERATED_MARK = "<!-- generated by farfield.viewers.indexes -->"
LOCK_NAME = ".farfield-indexes.lock"


class IndexRefreshError(RuntimeError):
    """The requested tree cannot be scanned or safely published."""


# Files worth surfacing on a dataset row when present.
DATASET_ASSETS = ("trajectory.png", "vehicle_anchor.png",
                  "gps_timelapse.mp4")

# These are collection containers under datasets/, not active datasets. Keep
# their children browsable without reporting the container itself as a
# zero-panorama dataset.
DATASET_COLLECTIONS = (
    "unvetted",
    "out_of_date_but_usable_mapillary_datasets",
)

# (directory suffix, page path, label), in display order. These paths are
# relative to an experiment index beside the run and its diagnostic siblings.
RUN_SIBLING_PAGES = (
    (".viewer", "viewer.html", "filter viewer"),
    (".plots", "map.png", "map"),
)

# Directories with these reserved suffixes are derived diagnostics or partial
# publications, not completed localization runs. Keep them out of run counts
# and rows even when the experiment directory contains no typed metadata.
RUN_SIDE_DIRECTORY_SUFFIXES = (
    ".viewer",
    ".plots",
    ".satellite",
    ".counterfactuals",
    ".attribution",
    artifact_lib.INCOMPLETE_SUFFIX,
)

FRAME_VIEWER_KIND = "frame_landmark_viewer"
FRAME_VIEWER_SCHEMA = "farfield_frame_landmark_viewer/v1"


def _require_directory(path: Path, *, allow_missing: bool = False) -> bool:
    """Validate one directory without following a final symlink."""
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        if allow_missing:
            return False
        raise IndexRefreshError(f"directory does not exist: {path}") from None
    if stat.S_ISLNK(metadata.st_mode):
        raise IndexRefreshError(f"refusing symlink directory: {path}")
    if not stat.S_ISDIR(metadata.st_mode):
        raise IndexRefreshError(
            f"expected directory, found another entry: {path}")
    return True


@contextmanager
def _exclusive_refresh_lock(data_root: Path):
    """Hold the persistent, root-local lock for one complete refresh."""
    lock_path = data_root / LOCK_NAME
    flags = os.O_RDWR | os.O_CREAT
    flags |= getattr(os, "O_CLOEXEC", 0)
    flags |= getattr(os, "O_NOFOLLOW", 0)
    flags |= getattr(os, "O_NONBLOCK", 0)
    try:
        descriptor = os.open(lock_path, flags, 0o600)
    except OSError as exc:
        raise IndexRefreshError(
            f"cannot open refresh lock as a regular file: {lock_path}") from exc
    try:
        if not stat.S_ISREG(os.fstat(descriptor).st_mode):
            raise IndexRefreshError(
                f"refresh lock is not a regular file: {lock_path}")
        fcntl.flock(descriptor, fcntl.LOCK_EX)
        yield
    finally:
        try:
            fcntl.flock(descriptor, fcntl.LOCK_UN)
        finally:
            os.close(descriptor)


def _write_index(directory: Path, html: str, skipped: list[str]) -> None:
    _require_directory(directory)
    target = Path(directory) / "index.html"
    try:
        target_metadata = target.lstat()
    except FileNotFoundError:
        pass
    else:
        if stat.S_ISLNK(target_metadata.st_mode):
            skipped.append(str(target))
            return
        if not stat.S_ISREG(target_metadata.st_mode):
            raise IndexRefreshError(
                f"index target is not a regular file: {target}")
        with target.open(errors="replace") as stream:
            ownership_header = stream.readline(256).rstrip("\r\n")
        if ownership_header != INDEX_GENERATED_MARK:
            skipped.append(str(target))
            return
    artifact_lib.atomic_write_file(target, html.encode("utf-8"))


def _manifest_summary(version_dir: Path) -> tuple:
    manifest = version_dir / "manifest.json"
    if not manifest.exists():
        return ("<span class='warn'>no manifest</span>", "")
    try:
        doc = json.loads(manifest.read_text())
    except json.JSONDecodeError:
        return ("<span class='bad'>unreadable manifest</span>", "")
    return (pg.esc(doc.get("generator", "?")),
            pg.esc(doc.get("created", "")))


def _frame_viewer_links(data_root: Path) -> dict[str, dict[tuple[str, str], Path]]:
    """Map exact frame/track dataset+versions to their newest sidecar.

    Navigation is a best-effort scan, not artifact validation.  The linked
    sidecar itself remains strictly manifested and validates its exact
    FRAME_LANDMARKS + OBJECT_TRACKS upstream identities when opened.
    """
    links = {"frame_landmarks": {}, "object_tracks": {}}
    created_by_key = {"frame_landmarks": {}, "object_tracks": {}}
    lane = data_root / "artifacts" / "frame_landmarks"
    for dataset_dir in _dirs(lane):
        for viewer_dir in _dirs(dataset_dir):
            manifest_path = viewer_dir / artifact_lib.MANIFEST_NAME
            try:
                document = json.loads(manifest_path.read_text())
            except (FileNotFoundError, OSError, UnicodeError,
                    json.JSONDecodeError):
                continue
            if (document.get("kind") != FRAME_VIEWER_KIND
                    or (document.get("config") or {}).get("schema")
                    != FRAME_VIEWER_SCHEMA
                    or not _regular_page(viewer_dir / "index.html")
                    or not _regular_page(viewer_dir / "tracks" / "index.html")):
                continue
            track_refs = [
                ref for ref in document.get("upstreams", [])
                if isinstance(ref, dict)
                and ref.get("kind") == "object_tracks"
            ]
            frame_refs = [
                ref for ref in document.get("upstreams", [])
                if isinstance(ref, dict)
                and ref.get("kind") == "frame_landmarks"
            ]
            if len(track_refs) != 1 or len(frame_refs) != 1:
                continue
            created = document.get("created", "")
            if not isinstance(created, str):
                created = ""
            for kind, reference in (
                    ("frame_landmarks", frame_refs[0]),
                    ("object_tracks", track_refs[0])):
                key = (reference.get("dataset"), reference.get("version"))
                if not all(isinstance(value, str) and value for value in key):
                    continue
                if (key not in links[kind]
                        or created > created_by_key[kind][key]):
                    links[kind][key] = viewer_dir
                    created_by_key[kind][key] = created
    return links


def _dirs(path: Path) -> list[Path]:
    if not _require_directory(path, allow_missing=True):
        return []
    directories = []
    for entry in path.iterdir():
        if entry.name.startswith("."):
            continue
        if entry.is_symlink() and entry.is_dir():
            raise IndexRefreshError(f"refusing symlink directory: {entry}")
        if entry.is_dir():
            directories.append(entry)
    return sorted(directories, key=lambda entry: entry.name)


def _run_dirs(experiment: Path) -> list[Path]:
    """Return completed run candidates, excluding sibling diagnostics."""
    return [
        path for path in _dirs(experiment)
        if not path.name.endswith(RUN_SIDE_DIRECTORY_SUFFIXES)
    ]


def _regular_page(path: Path) -> bool:
    """Return whether one page exists, rejecting unsafe filesystem entries."""
    try:
        metadata = path.lstat()
    except FileNotFoundError:
        return False
    if stat.S_ISLNK(metadata.st_mode):
        raise IndexRefreshError(f"refusing symlink page: {path}")
    if not stat.S_ISREG(metadata.st_mode):
        raise IndexRefreshError(f"page is not a regular file: {path}")
    return True


def _panorama_directory(dataset: Path) -> Path | None:
    """Return a safe panorama directory, including ``panorama -> frames``.

    Dataset storage deliberately uses a relative in-dataset symlink so the
    same frame bytes have one owner. Index generation may follow that exact
    shape, but never an absolute, dangling, or dataset-escaping link.
    """
    panorama = dataset / "panorama"
    try:
        metadata = panorama.lstat()
    except FileNotFoundError:
        return None
    if stat.S_ISDIR(metadata.st_mode):
        return panorama
    if not stat.S_ISLNK(metadata.st_mode):
        raise IndexRefreshError(
            f"panorama entry is neither a directory nor symlink: {panorama}")
    target_text = os.readlink(panorama)
    if Path(target_text).is_absolute():
        raise IndexRefreshError(
            f"refusing absolute panorama symlink: {panorama} -> {target_text}")
    if target_text != "frames":
        raise IndexRefreshError(
            f"panorama symlink target must be exactly 'frames': "
            f"{panorama} -> {target_text}")
    frames = dataset / "frames"
    try:
        target = panorama.resolve(strict=True)
        expected = dataset.resolve(strict=True) / "frames"
    except (FileNotFoundError, RuntimeError) as exc:
        raise IndexRefreshError(
            f"refusing dangling panorama symlink: "
            f"{panorama} -> {target_text}") from exc
    try:
        frames_metadata = frames.lstat()
    except FileNotFoundError as exc:
        raise IndexRefreshError(
            f"refusing dangling panorama symlink: "
            f"{panorama} -> {target_text}") from exc
    if (stat.S_ISLNK(frames_metadata.st_mode)
            or not stat.S_ISDIR(frames_metadata.st_mode)
            or target != expected):
        raise IndexRefreshError(
            f"panorama symlink must resolve to the real in-dataset frames "
            f"directory: {panorama} -> {target_text}")
    return panorama


def _dataset_row(dataset: Path, *, href_prefix: str = "") -> list[str]:
    assets = " ".join(
        f'<a href="{href_prefix}{dataset.name}/{name}">'
        f'{name.split(".")[0]}</a>'
        for name in DATASET_ASSETS if (dataset / name).exists())
    panorama = _panorama_directory(dataset)
    n_panoramas = len(list(panorama.glob("*.jpg"))) if panorama else 0
    return [
        f'<a href="{href_prefix}{dataset.name}/">'
        f'{pg.esc(dataset.name)}</a>',
        str(n_panoramas),
        assets or "<span class='muted'>—</span>",
    ]


def _run_page_links(run: Path) -> list[tuple[str, str]]:
    """Resolve sibling pages without probing the immutable run directory."""
    links = []
    for suffix, relative, label in RUN_SIBLING_PAGES:
        directory = run.with_name(run.name + suffix)
        if not _require_directory(directory, allow_missing=True):
            continue
        if _regular_page(directory / relative):
            links.append((f"{directory.name}/{relative}", label))
    return links


def refresh(data_root: Path) -> dict:
    """Regenerate a snapshot under one lock, replacing each page atomically.

    Returns {"written": [...], "skipped": [...]} where skipped lists
    index.html files owned by something else.
    """
    data_root = Path(data_root)
    _require_directory(data_root)
    with _exclusive_refresh_lock(data_root):
        return _refresh_locked(data_root)


def _refresh_locked(data_root: Path) -> dict:
    written, skipped = [], []

    def emit(directory, title, body, crumbs):
        html = (f"{INDEX_GENERATED_MARK}\n" +
                pg.page(title, body, generator=GENERATOR, crumbs=crumbs))
        before = len(skipped)
        _write_index(directory, html, skipped)
        if len(skipped) == before:
            written.append(str(Path(directory) / "index.html"))

    # --- datasets lane -----------------------------------------------------
    dataset_entries = _dirs(data_root / "datasets")
    collections = [entry for entry in dataset_entries
                   if entry.name in DATASET_COLLECTIONS]
    datasets = [entry for entry in dataset_entries
                if entry.name not in DATASET_COLLECTIONS]
    rows = [_dataset_row(dataset) for dataset in datasets]
    collection_rows = []
    for collection in collections:
        children = _dirs(collection)
        emit(collection, f"datasets / {collection.name}",
             pg.table(["dataset", "panoramas", "assets"],
                      [_dataset_row(child) for child in children]),
             [("farfield", "../../index.html"),
              ("datasets", "../index.html"), (collection.name, None)])
        collection_rows.append([
            f'<a href="{collection.name}/index.html">'
            f'{pg.esc(collection.name)}</a>', str(len(children))])
    if _require_directory(data_root / "datasets", allow_missing=True):
        body = pg.table(["dataset", "panoramas", "assets"], rows)
        if collection_rows:
            body += "\n<h2>collections</h2>\n" + pg.table(
                ["collection", "datasets"], collection_rows)
        emit(data_root / "datasets", "datasets",
             body,
             [("farfield", "../index.html"), ("datasets", None)])

    # --- artifacts lane ----------------------------------------------------
    kinds = _dirs(data_root / "artifacts")
    frame_viewers = _frame_viewer_links(data_root)
    for kind in kinds:
        krows = []
        for ds in _dirs(kind):
            versions = _dirs(ds)
            cells = []
            for version in versions:
                generator, created = _manifest_summary(version)
                inner = (f'<a href="{ds.name}/{version.name}/">'
                         f'{pg.esc(version.name)}</a>')
                # Link a version's own index page when a stage produced one.
                if (version / "index.html").exists():
                    inner = (f'<a href="{ds.name}/{version.name}/'
                             f'index.html">{pg.esc(version.name)}</a>')
                viewer = frame_viewers["object_tracks"].get(
                    (ds.name, version.name))
                if kind.name == "object_tracks" and viewer is not None:
                    viewer_href = (
                        f"../frame_landmarks/{ds.name}/{viewer.name}/"
                        "tracks/index.html")
                    inner += (f' · <a href="{viewer_href}">'
                              "frames ↔ tracks</a>")
                viewer = frame_viewers["frame_landmarks"].get(
                    (ds.name, version.name))
                if kind.name == "frame_landmarks" and viewer is not None:
                    viewer_href = f"{ds.name}/{viewer.name}/index.html"
                    inner += (f' · <a href="{viewer_href}">keyframes</a>')
                cells.append(f"{inner} <span class='muted'>{generator} "
                             f"{created}</span>")
            krows.append([f"{pg.esc(ds.name)}", "<br>".join(cells)])
        emit(kind, f"artifacts / {kind.name}",
             pg.table(["dataset", "versions"], krows),
             [("farfield", "../../index.html"),
              ("artifacts", "../index.html"), (kind.name, None)])
    if _require_directory(data_root / "artifacts", allow_missing=True):
        emit(data_root / "artifacts", "artifacts",
             pg.table(["kind", "datasets"], [
                 [f'<a href="{k.name}/index.html">{pg.esc(k.name)}</a>',
                  str(len(_dirs(k)))] for k in kinds]),
             [("farfield", "../index.html"), ("artifacts", None)])

    # --- runs lane (experiments) --------------------------------------------
    experiments = _dirs(data_root / "runs")
    for experiment in experiments:
        body_parts = []
        notes = experiment / "experiment.md"
        if notes.exists():
            body_parts.append(pg.render_markdown_lite(notes.read_text()))
        else:
            body_parts.append(
                "<p class='warn'>no experiment.md — every experiment "
                "directory carries one (what is being explored, status, "
                "conclusions).</p>")
        run_rows = []
        for run in _run_dirs(experiment):
            links = " · ".join(
                f'<a href="{relative}">{label}</a>'
                for relative, label in _run_page_links(run))
            run_rows.append([pg.esc(run.name),
                             links or "<span class='muted'>no pages</span>"])
        body_parts.append(pg.table(["run", "pages"], run_rows))
        emit(experiment, experiment.name, "\n".join(body_parts),
             [("farfield", "../../index.html"), ("runs", "../index.html"),
              (experiment.name, None)])
    if _require_directory(data_root / "runs", allow_missing=True):
        rows = []
        for experiment in experiments:
            first_line = ""
            notes = experiment / "experiment.md"
            if notes.exists():
                for line in notes.read_text().splitlines():
                    if line.strip() and not line.startswith("#"):
                        first_line = line.strip()
                        break
            rows.append([
                f'<a href="{experiment.name}/index.html">'
                f'{pg.esc(experiment.name)}</a>',
                str(len(_run_dirs(experiment))), pg.esc(first_line)])
        emit(data_root / "runs", "runs (experiments)",
             pg.table(["experiment", "runs", "summary"], rows),
             [("farfield", "../index.html"), ("runs", None)])

    # --- root ----------------------------------------------------------------
    lane_rows = []
    for lane, blurb in (("datasets", "frozen problem definitions"),
                        ("artifacts", "derived per-dataset products"),
                        ("runs", "experiments (localization runs)"),
                        ("models", "weights"),
                        ("raw_material", "source material")):
        path = data_root / lane
        if not _require_directory(path, allow_missing=True):
            continue
        href = (f"{lane}/index.html"
                if (path / "index.html").exists()
                or lane in ("datasets", "artifacts", "runs") else f"{lane}/")
        lane_rows.append([f'<a href="{href}">{pg.esc(lane)}</a>',
                          str(len(_dirs(path))), pg.esc(blurb)])
    emit(data_root, "farfield data root",
         pg.table(["lane", "entries", ""], lane_rows),
         None)

    return {"written": written, "skipped": skipped}
