"""The one HTML page helper for farfield viewers.

Two entry points, because farfield has two kinds of viewer and forcing them
into one shape is what pushed the big ones out of this module in the first
place:

- `page()` builds a stage/index page: shared stylesheet, a title heading,
  optional breadcrumbs. Most viewers want exactly this.
- `document()` builds only the skeleton -- generated mark, doctype, head,
  body -- and takes the caller's own stylesheet. The localization run viewer
  and the match viewer are full designs with their own type scale, layout and
  header; they need the skeleton's guarantees, not this module's look.

`page()` is written in terms of `document()`, so there is one definition of
what a farfield page *is*. That matters for two properties every page must
have and neither of the big viewers had while it rendered its own document:

- `GENERATED_MARK`, which `indexes.refresh` requires before it will overwrite
  a page -- an unmarked page is indistinguishable from something hand-written
  that a regeneration would destroy;
- a provenance footer naming the generator, git commit and time, so a stale
  page identifies itself instead of looking current.

Pages are self-contained static HTML with relative links and no network:
`python -m http.server` at the data root must render everything.
"""

import html as html_lib
from datetime import datetime, timezone

from experimental.overhead_matching.swag.farfield import provenance

STYLE = """
body { font-family: system-ui, sans-serif; background: #14171c; color: #d8dce2;
       margin: 0; padding: 24px; line-height: 1.5; }
a { color: #7fb4e8; text-decoration: none; }
a:hover { text-decoration: underline; }
h1 { font-size: 22px; margin: 0 0 4px; }
h2 { font-size: 16px; margin: 24px 0 8px; color: #aab3bf; }
table { border-collapse: collapse; margin-top: 10px; }
td, th { padding: 4px 12px; font-size: 13px; border-bottom: 1px solid #2a2f38;
         text-align: left; vertical-align: top; }
th { color: #8a94a3; font-weight: 600; }
code, pre { background: #1d222a; border-radius: 3px; }
code { padding: 1px 5px; font-size: 12px; }
pre { padding: 10px 14px; overflow-x: auto; font-size: 12px; }
.muted { color: #79828f; font-size: 12px; }
.warn { color: #e0a04a; }
.bad { color: #e06c6c; }
.ok { color: #6fbf73; }
.crumbs { font-size: 12px; color: #79828f; margin-bottom: 14px; }
footer.provenance { margin-top: 36px; padding-top: 10px;
       border-top: 1px solid #2a2f38; font-size: 11px; color: #616a76; }
"""

GENERATED_MARK = "<!-- generated by farfield.viewers -->"


def esc(text) -> str:
    return html_lib.escape(str(text))


def provenance_footer(generator: str, *,
                      css_class: str = "provenance",
                      style: str = "") -> str:
    """The footer every farfield page carries.

    Without it a page that was regenerated last month and one regenerated
    this morning look identical, which is how a viewer gets read as current
    evidence for a run it no longer describes.
    """
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    attribute = f' style="{esc(style)}"' if style else ""
    return (f'<footer class="{esc(css_class)}"{attribute}>{esc(generator)} · '
            f"git {esc(provenance.git_commit()[:12])} · {esc(stamp)}"
            f"</footer>")


def document(title: str, body: str, *, style: str,
             viewport: bool = True) -> str:
    """The skeleton shared by every farfield page.

    Deliberately opinionated about exactly three things -- the generated
    mark, a well-formed head, and that the caller's stylesheet is the only
    one applied -- and about nothing else. A viewer with its own design
    passes its own `style` and builds its own header; it still cannot end up
    without the mark or with a head missing a charset.
    """
    meta_viewport = ('<meta name="viewport" '
                     'content="width=device-width,initial-scale=1">'
                     if viewport else "")
    return (
        f"{GENERATED_MARK}\n<!DOCTYPE html>\n<html lang=\"en\"><head>"
        f"<meta charset=\"utf-8\">{meta_viewport}"
        f"<title>{esc(title)}</title>"
        f"<style>{style}</style></head><body>{body}</body></html>\n")


def page(title: str, body: str, *, generator: str,
         crumbs: list | None = None, extra_style: str = "") -> str:
    """A stage or index page in the shared farfield style.

    generator: the producing module/target — stamped in the footer with the
    git commit and time, so a stale page identifies itself.
    crumbs: [(label, relative_href), ...] breadcrumb links; the last entry
    may have href None for the current page.
    """
    crumb_html = ""
    if crumbs:
        parts = []
        for label, href in crumbs:
            parts.append(f'<a href="{esc(href)}">{esc(label)}</a>'
                         if href else esc(label))
        crumb_html = f'<div class="crumbs">{" / ".join(parts)}</div>'
    return document(
        title,
        f"{crumb_html}<h1>{esc(title)}</h1>\n{body}\n"
        + provenance_footer(generator),
        style=STYLE + extra_style)


def table(headers: list, rows: list) -> str:
    """rows: lists of cell HTML (caller escapes text cells with esc())."""
    head = "".join(f"<th>{esc(h)}</th>" for h in headers)
    body = "\n".join(
        "<tr>" + "".join(f"<td>{cell}</td>" for cell in row) + "</tr>"
        for row in rows)
    return f"<table><tr>{head}</tr>\n{body}</table>"


def render_markdown_lite(text: str) -> str:
    """Minimal markdown for experiment.md pages: headers, lists, code
    fences, paragraphs. Deliberately tiny — anything fancier belongs in a
    real doc, not an index page."""
    out, in_code, in_list, paragraph = [], False, False, []

    def flush_paragraph():
        if paragraph:
            out.append(f"<p>{esc(' '.join(paragraph))}</p>")
            paragraph.clear()

    def close_list():
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    for line in text.splitlines():
        if line.strip().startswith("```"):
            flush_paragraph()
            close_list()
            out.append("<pre>" if not in_code else "</pre>")
            in_code = not in_code
            continue
        if in_code:
            out.append(esc(line))
            continue
        stripped = line.strip()
        if not stripped:
            flush_paragraph()
            close_list()
        elif stripped.startswith("#"):
            flush_paragraph()
            close_list()
            level = min(len(stripped) - len(stripped.lstrip("#")), 3)
            out.append(f"<h{level + 1}>{esc(stripped.lstrip('# '))}"
                       f"</h{level + 1}>")
        elif stripped.startswith(("- ", "* ")):
            flush_paragraph()
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{esc(stripped[2:])}</li>")
        else:
            paragraph.append(stripped)
    flush_paragraph()
    close_list()
    if in_code:
        out.append("</pre>")
    return "\n".join(out)
