"""The one HTML page helper for farfield viewers.

Every stage viewer builds its page through `page()` so the tree has ONE
stylesheet (the old stages carried 14 divergent inline copies of the same
CSS) and every page gets a provenance footer for free (generator, git
commit, timestamp) — the audit's "no viewer records what made it" fix.

Pages are self-contained static HTML with relative links and no network:
`python -m http.server` at the data root must render everything.
"""

import html as html_lib
from datetime import datetime, timezone

from experimental.overhead_matching.swag.farfield import provenance

STYLE = """
body { font-family: system-ui, sans-serif; background: #14171c; color: #d8dce2;
       margin: 0; padding: 24px; line-height: 1.5; }
a { color: #7fb4e8; text-decoration: none; }
a:hover { text-decoration: underline; }
h1 { font-size: 22px; margin: 0 0 4px; }
h2 { font-size: 16px; margin: 24px 0 8px; color: #aab3bf; }
table { border-collapse: collapse; margin-top: 10px; }
td, th { padding: 4px 12px; font-size: 13px; border-bottom: 1px solid #2a2f38;
         text-align: left; vertical-align: top; }
th { color: #8a94a3; font-weight: 600; }
code, pre { background: #1d222a; border-radius: 3px; }
code { padding: 1px 5px; font-size: 12px; }
pre { padding: 10px 14px; overflow-x: auto; font-size: 12px; }
.muted { color: #79828f; font-size: 12px; }
.warn { color: #e0a04a; }
.bad { color: #e06c6c; }
.ok { color: #6fbf73; }
.crumbs { font-size: 12px; color: #79828f; margin-bottom: 14px; }
footer.provenance { margin-top: 36px; padding-top: 10px;
       border-top: 1px solid #2a2f38; font-size: 11px; color: #616a76; }
"""

GENERATED_MARK = "<!-- generated by farfield.viewers -->"


def esc(text) -> str:
    return html_lib.escape(str(text))


def page(title: str, body: str, *, generator: str,
         crumbs: list | None = None, extra_style: str = "") -> str:
    """A complete HTML document.

    generator: the producing module/target — stamped in the footer with the
    git commit and time, so a stale page identifies itself.
    crumbs: [(label, relative_href), ...] breadcrumb links; the last entry
    may have href None for the current page.
    """
    crumb_html = ""
    if crumbs:
        parts = []
        for label, href in crumbs:
            parts.append(f'<a href="{esc(href)}">{esc(label)}</a>'
                         if href else esc(label))
        crumb_html = f'<div class="crumbs">{" / ".join(parts)}</div>'
    stamp = datetime.now(timezone.utc).isoformat(timespec="seconds")
    return (
        f"{GENERATED_MARK}\n<!DOCTYPE html>\n<html><head>"
        f"<meta charset=\"utf-8\"><title>{esc(title)}</title>"
        f"<style>{STYLE}{extra_style}</style></head><body>"
        f"{crumb_html}<h1>{esc(title)}</h1>\n{body}\n"
        f"<footer class=\"provenance\">{esc(generator)} · "
        f"git {esc(provenance.git_commit()[:12])} · {esc(stamp)}"
        f"</footer></body></html>\n")


def table(headers: list, rows: list) -> str:
    """rows: lists of cell HTML (caller escapes text cells with esc())."""
    head = "".join(f"<th>{esc(h)}</th>" for h in headers)
    body = "\n".join(
        "<tr>" + "".join(f"<td>{cell}</td>" for cell in row) + "</tr>"
        for row in rows)
    return f"<table><tr>{head}</tr>\n{body}</table>"


def render_markdown_lite(text: str) -> str:
    """Minimal markdown for experiment.md pages: headers, lists, code
    fences, paragraphs. Deliberately tiny — anything fancier belongs in a
    real doc, not an index page."""
    out, in_code, in_list, paragraph = [], False, False, []

    def flush_paragraph():
        if paragraph:
            out.append(f"<p>{esc(' '.join(paragraph))}</p>")
            paragraph.clear()

    def close_list():
        nonlocal in_list
        if in_list:
            out.append("</ul>")
            in_list = False

    for line in text.splitlines():
        if line.strip().startswith("```"):
            flush_paragraph()
            close_list()
            out.append("<pre>" if not in_code else "</pre>")
            in_code = not in_code
            continue
        if in_code:
            out.append(esc(line))
            continue
        stripped = line.strip()
        if not stripped:
            flush_paragraph()
            close_list()
        elif stripped.startswith("#"):
            flush_paragraph()
            close_list()
            level = min(len(stripped) - len(stripped.lstrip("#")), 3)
            out.append(f"<h{level + 1}>{esc(stripped.lstrip('# '))}"
                       f"</h{level + 1}>")
        elif stripped.startswith(("- ", "* ")):
            flush_paragraph()
            if not in_list:
                out.append("<ul>")
                in_list = True
            out.append(f"<li>{esc(stripped[2:])}</li>")
        else:
            paragraph.append(stripped)
    flush_paragraph()
    close_list()
    if in_code:
        out.append("</pre>")
    return "\n".join(out)
