"""Focused contract tests for the causal grid viewer."""

import types
import unittest

from experimental.overhead_matching.swag.farfield import artifact
from experimental.overhead_matching.swag.farfield.localization import grid_viewer


class GridViewerTest(unittest.TestCase):

    def setUp(self):
        self.reference = artifact.ArtifactRef(
            path="/irrelevant/export", kind="localization_inputs",
            dataset="tiny", version="v1", manifest_digest="1" * 64,
            content_digest="2" * 64)
        self.data = types.SimpleNamespace(
            n_keyframes=2,
            artifact_ref=self.reference,
            truth=[
                types.SimpleNamespace(east_m=0.0, north_m=0.0),
                types.SimpleNamespace(east_m=3.0, north_m=4.0),
            ])
        self.result = {
            "schema": grid_viewer.SCHEMA,
            "localization_inputs": self.reference.to_dict(),
            "mass_by_keyframe": {"500": [0.25, 0.75]},
            "map_error_m_by_keyframe": [0.0, 5.0],
            "online_map_state_by_keyframe": {"states": [
                {"east_m": 0.0, "north_m": 0.0,
                 "heading_world_cw_deg": 0.0},
                {"east_m": 0.0, "north_m": 0.0,
                 "heading_world_cw_deg": 90.0},
            ]},
        }

    def test_state_trace_rejects_missing_online_trace_and_error_mismatch(self):
        legacy = dict(self.result)
        legacy["map_state_by_keyframe"] = legacy.pop(
            "online_map_state_by_keyframe")
        with self.assertRaisesRegex(ValueError, "online MAP state trace"):
            grid_viewer._state_trace(legacy, self.data)  # noqa: SLF001

        states = grid_viewer._state_trace(  # noqa: SLF001
            self.result, self.data)
        grid_viewer._validate_result(  # noqa: SLF001
            self.result, self.data, states)
        mismatched = dict(self.result)
        mismatched["map_error_m_by_keyframe"] = [0.0, 4.0]
        with self.assertRaisesRegex(ValueError, "position-marginal MAP trace"):
            grid_viewer._validate_result(  # noqa: SLF001
                mismatched, self.data, states)

    def test_render_is_self_contained_and_escapes_hostile_values(self):
        hostile = "</script><img src=x onerror=alert(1)>"
        payload = {
            "scenario": hostile,
            "dataset": "tiny",
            "availability": "natural",
            "tail": "uniform",
            "nKeyframes": 2,
            "grid": {"box": [-10.0, 10.0, -10.0, 10.0],
                     "cellM": 1.0, "nHeading": 4},
            "summary": {},
            "truth": [{"e": 0.0, "n": 0.0}, {"e": 3.0, "n": 4.0}],
            "states": [{"e": 0.0, "n": 0.0, "h": 0.0},
                       {"e": 0.0, "n": 0.0, "h": 90.0}],
            "mass500": [0.25, 0.75],
            "errors": [0.0, 5.0],
            "finalModes": [],
            "landmarks": [{"id": hostile, "type": "tower", "e": 1.0,
                           "n": 2.0, "osm": None}],
            "tracks": [{
                "id": "global#T1", "label": "T1", "release": 1,
                "anchors": [{"kf": 0, "bearing": 10.0, "sigma": 2.0,
                             "range": None}],
                "candidates": [{"id": hostile, "lr": 1.0}], "floor": -4.0,
                "trackHref": "../../tracks/track_full_T1.html",
                "matcherHref": "../../matches/index.html#T1",
                "auditHref": "../../audits/preview/index.html#T1",
            }],
        }
        rendered = grid_viewer.render_html(payload)
        self.assertTrue(rendered.startswith("<!-- generated by farfield.viewers -->"))
        self.assertNotIn(hostile, rendered)
        self.assertIn("\\u003c/script\\u003e", rendered)
        self.assertIn("not a smoothed or Viterbi trajectory", rendered)
        self.assertIn("grid method has no particles", rendered)
        self.assertIn("../../tracks/track_full_T1.html", rendered)
        self.assertIn('return track.release===t?"new"', rendered)
        self.assertNotIn("fetch(", rendered)
        self.assertNotIn('<script src=', rendered)


if __name__ == "__main__":
    unittest.main()
