"""Typed messages and run-artifact records for bearing-only localization.

Configs and interface messages are tagged + frozen (MSGSPEC_STRUCT_OPTS);
per-keyframe log records are plain mutable Structs.

The CompatibilityTable is the matcher-seam contract (design doc §6).
TrackletMeasurement is the sparse information-epoch event of §5.3: one fused
body-frame bearing per tracklet per epoch, anchored at a keyframe.

Angle contract: `bearing_body_deg` is relative to vehicle heading, degrees
clockwise positive, stored in **[0, 360)** — every producer normalizes with
`% 360` before serializing, and consumers compare angles with the wrap
helpers in `farfield.geometry`, never by subtraction. Nothing upstream is
assumed north-aligned.

Tuning provenance: several defaults below were set by measured experiments on
the harbor/mountain datasets. The numbers are the record; the experiment
narratives live in docs/farfield (they used to live inline here, which made
this file half lab notebook).
"""

import msgspec

from common.python.serialization import MSGSPEC_STRUCT_OPTS

SCHEMA_VERSION = "0.3"  # 0.3: RunManifest carries required provenance fields


class LandmarkEntry(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Catalog stub: one known-position landmark."""
    landmark_id: str
    lat_deg: float
    lon_deg: float
    type_key: str


class CompatibilityEntry(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    landmark_id: str
    log_lr: float


class CompatibilityTable(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Matcher-seam output for one tracklet (design doc §6).

    Landmarks absent from `entries` score `default_log_lr`. The filter clips
    every log_lr to [clip_lo, clip_hi]; with an uncalibrated matcher the
    clips and the null hypothesis carry the safety burden.
    """
    tracklet_id: str
    matcher_version: str
    entries: list[CompatibilityEntry]
    default_log_lr: float
    clip_lo: float
    clip_hi: float
    status: str  # "fast" | "refined"


class TrackletMeasurement(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """One information epoch of one tracklet: a fused body-frame bearing."""
    tracklet_id: str
    anchor_keyframe_idx: int
    bearing_body_deg: float  # CW from vehicle heading, in [0, 360)
    kappa: float  # von Mises concentration of the fused bearing


class OdometryDelta(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Body-frame SE(2) increment from keyframe_idx-1 to keyframe_idx (§5.2).

    The generic dead-reckoning contract every relative-motion sensor speaks
    (IMU, VIO, wheel, water log): x forward, y left. `dyaw_rad` is required —
    a producer with no usable yaw signal for a step emits 0 with
    `sigma_yaw_rad` inflated to a random-walk budget. Translation noise is
    isotropic on purpose: cross-track uncertainty is generated by heading
    uncertainty when the filter rotates the increment through each particle's
    heading, so a separate cross-track sigma would double-count it.
    """
    keyframe_idx: int
    forward_m: float
    left_m: float
    dyaw_rad: float
    sigma_m: float  # isotropic per-axis translation noise std
    sigma_yaw_rad: float


class GaussianInit(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Local prior: isotropic Gaussian position, uniform heading."""
    mean_east_m: float
    mean_north_m: float
    sigma_m: float


class UniformBoxInit(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Global prior: uniform position over a box, uniform heading."""
    east_min_m: float
    east_max_m: float
    north_min_m: float
    north_max_m: float


class ProposalConfig(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Mixture proposal for global init and recovery (design doc §5.5).

    Defaults are the tuned production values; every one is echoed into the
    run manifest, so a run's numbers are always its own record.
    """
    enabled: bool = True
    # Fire at the first keyframe carrying bearings so the initial belief
    # comes from resected poses rather than a uniform box. Only honored for
    # an UNINFORMATIVE prior (UniformBoxInit): init-injecting into a local
    # Gaussian prior hands an uncalibrated matcher the belief (§5.5).
    on_init: bool = True
    # Kidnapped detection fires on the FRACTION of recent measurements that
    # were null-dominated, not on a consecutive run: a displaced belief
    # re-explains some bearings with wrong landmarks, so null share
    # alternates rather than pinning high. Healthy tracking sits near 0.
    null_share_threshold: float = 0.8
    null_share_window: int = 8
    null_share_min_fraction: float = 0.25
    # Fire when ESS stays below this fraction of n_particles for this many
    # consecutive keyframes — sustained collapse, not the single-keyframe
    # dip a diffuse prior takes on its first informative measurement.
    ess_floor_frac: float = 0.02
    ess_floor_keyframes: int = 3
    # Minimum keyframes between events; recovery needs time to take hold.
    refractory_keyframes: int = 10

    # Hypothesis generation.
    # Candidate identities per tracklet, from its table's top entries. Must
    # be large enough to enumerate a matcher tie whole — truncating inside a
    # tie means confidently resecting from a coin-flip identity.
    top_k_landmarks: int = 64
    max_tracklets: int = 5
    # Per-kind combination budgets, spent cheapest-kind-first so a
    # three-landmark explosion cannot starve the always-available
    # single-landmark hypotheses. A combination that does not fit the
    # remaining budget is skipped WHOLE, never enumerated part-way.
    max_combinations_single: int = 512
    max_combinations_pair: int = 4000
    max_combinations_triple: int = 8000
    max_hypotheses_per_kind: int = 256
    # Resection residual tolerance, in standard deviations of the bearing
    # measurement. It MUST scale with sigma — the residual of a true fix
    # grows with bearing noise, so a fixed ceiling rejects real solutions.
    residual_tolerance_sigma: float = 3.0
    max_residual_tolerance_deg: float = 90.0
    # Bearings within this many keyframes of the trigger are treated as
    # simultaneous (staggered epochs rarely put two bearings on one
    # keyframe; the induced angular error is under the bearing noise).
    window_keyframes: int = 4

    # Evidence gate on injection (§5.5): a fired trigger may displace belief
    # mass only when the proposal's best hypothesis explains the recent
    # bearing window better than every existing mode does, by this margin.
    # With no modes to protect (global init, modes disabled) the gate passes.
    evidence_gate: bool = True
    evidence_gate_margin_nats: float = 1.0
    # Charge log(n_hypotheses) for choosing the best of N hypotheses that
    # were each constructed to explain the very window they are scored on —
    # the multiple-comparisons correction one level up. Without it the flat
    # margin gets EASIER to clear the more hypotheses an event generates.
    # Never disable this because a broken-data run looked worse: on data
    # where the filter tracks, the charge is what stops a late marginal
    # injection from destroying a converged belief.
    evidence_gate_selection_charge: bool = True
    # OBSERVABILITY, not a tuning knob: a pose is three unknowns and one
    # bearing is one equation, so an injection resected from fewer than
    # three tracklets is a smear masquerading as a fix. Applied to the INIT
    # trigger only — a recovery injection is rescuing a failing belief,
    # where a broad-but-containing family beats a confident wrong point.
    min_tracklets_for_injection: int = 3
    # ... but not forever: a sparse leg may never show three at once, and
    # firing late beats brute-forcing a region-sized uniform box.
    init_max_wait_keyframes: int = 40
    # Poses sampled per hypothesis when scoring it against the window.
    evidence_gate_samples: int = 16

    # How injected mass is split across hypothesis kinds (renormalized over
    # the kinds actually generated). Triples are sharp but few; singles are
    # broad but always available and still collapse the heading axis.
    share_triple: float = 0.5
    share_pair: float = 0.35
    share_single: float = 0.15

    # Injection.
    # Fraction of particle mass replaced by proposed poses. Do NOT tune
    # this DOWN to be cautious — the effect is not monotonic: a partial
    # injection drags the belief toward a wrong hypothesis without leaving
    # enough mass on the alternatives to keep the posterior honest.
    inject_fraction: float = 0.5
    # FLOOR on the injected spread, not the spread itself: each hypothesis
    # carries its own spread (~sigma_bearing * range), and this only bounds
    # it below so a coarse fix is stated at the precision it actually has.
    injection_sigma_m: float = 100.0
    injection_heading_sigma_deg: float = 3.0
    # Ceiling, so one hopeless bearing cannot smear particles region-wide.
    max_injection_sigma_m: float = 2000.0


class ModeConfig(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Belief clustering for mode tracking (design doc §5.1/§5.6)."""
    enabled: bool = True
    cell_size_m: float = 150.0
    heading_cell_deg: float = 20.0
    # Cells lighter than this are noise, not part of any mode.
    min_cell_weight: float = 1e-4
    # A cluster must hold this much posterior mass to be called a mode.
    min_mode_weight: float = 0.02


class FilterConfig(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    n_particles: int
    seed: int
    init: GaussianInit | UniformBoxInit
    # Per-tracklet-class null-hypothesis probability. 0.2 rather than a
    # token few percent: with an uncalibrated matcher (§6) the null is what
    # stops the filter chasing accidentally-aligned clutter into a
    # confident wrong fix, and VLM false positives are common.
    pi0: float = 0.2
    ess_resample_frac: float = 0.5
    # Heading random-walk noise per keyframe, in quadrature with each
    # increment's own sigma_yaw_rad: the hedge for yaw drift the producer
    # does not declare. Deleting this hedge nulls the bearings.
    heading_random_walk_deg: float = 1.0
    # Kernel bandwidth for regularized resampling, as a multiple of the
    # Silverman-style rule sigma * n^(-1/6). Required for consistency: at 0
    # the resampled cloud collapses to duplicated atoms and the filter
    # reports a spread it no longer represents.
    resample_regularization: float = 1.0
    # Absolute jitter floors added on top of the kernel bandwidth, for
    # beliefs too collapsed for a proportional bandwidth to recover.
    position_roughening_m: float = 0.0
    heading_roughening_deg: float = 0.0
    # Bin size for the highest-density (MAP) position estimate.
    map_cell_size_m: float = 50.0
    checkpoint_every: int = 10
    # "numpy" (reference, bit-stable, CPU) or "torch" (GPU, float32; same
    # mixture, reductions differ at fp32 epsilon). Recorded so the manifest
    # states which engine produced a run.
    measurement_backend: str = "numpy"
    # §5.3 association persistence: a tracklet is ONE physical object, so
    # its identity persists across its epochs under a renewal HMM.
    # Marginalizing independently per epoch re-pays the 1/|catalog|
    # candidate prior on EVERY epoch, coupling bearing evidence to catalog
    # size; persistence pays it once per tracklet.
    association_persistence: bool = True
    # beta: per-epoch probability the tracklet's physical identity switched
    # (track swaps at occlusions are tracker behavior, not map behavior).
    association_renewal_rate: float = 0.1
    # eps: outlier rate within a correct association — a committed tracklet
    # can still emit a bad bearing (partial occlusion, panorama seam).
    association_outlier_rate: float = 0.1
    # Probability the true landmark appears among a table's ENDORSED
    # entries (given any exist) — a matcher property used to build the
    # proper identity posterior. Without it, a whole-map catalog claims the
    # true landmark is almost surely one the matcher rejected.
    matcher_recall: float = 0.5
    # Responsibilities below this are dropped from REPORTED association
    # posteriors (likelihoods are never truncated); whole-map catalogs make
    # the dense dicts dominate run time and artifact size otherwise.
    min_reported_responsibility: float = 1e-6
    proposal: ProposalConfig = msgspec.field(default_factory=ProposalConfig)
    modes: ModeConfig = msgspec.field(default_factory=ModeConfig)


class ModeRecord(msgspec.Struct):
    """One mode at one keyframe."""
    mode_id: int
    weight: float
    n_particles: int
    mean_east_m: float
    mean_north_m: float
    mean_heading_deg: float
    position_std_m: float
    heading_std_deg: float
    birth_keyframe_idx: int
    parent_mode_ids: list[int] = []
    # Where this mode came from: motion-model descent, or a proposal event
    # with the tracklets/landmarks that generated it (§5.5 [CONTRACT]).
    provenance: dict[str, str | int] = {}


class ModeEvent(msgspec.Struct):
    """Birth, death or merge — the §7.3 auto-bookmarks for mode bookkeeping."""
    keyframe_idx: int
    kind: str  # "birth" | "death" | "merge"
    mode_id: int
    parent_mode_ids: list[int] = []
    detail: dict[str, str | int] = {}


class AssociationPosterior(msgspec.Struct):
    """Per-measurement association responsibilities (design doc §5.4).

    [CONTRACT] Reported PER MODE (`mode_id` set), not only averaged over the
    whole belief: for a multimodal posterior the global average blends two
    contradictory explanations into a number describing neither. The
    whole-belief average is still emitted, with mode_id None.
    """
    tracklet_id: str
    anchor_keyframe_idx: int
    null_share: float
    responsibilities: dict[str, float] = {}
    mode_id: int | None = None
    # Share of the group's mass explaining this tracklet through a
    # candidate the matcher does NOT vouch for: identity surprise. A
    # displaced belief re-explains bearings with wrong landmarks — cheaply
    # visible here, invisible to null share (§8.4).
    surprise_share: float = 0.0


class HealthRecord(msgspec.Struct):
    """Tier-0 health scalars, one per keyframe (design doc §5.6/§7.1).

    All belief statistics describe the WEIGHTED posterior at this keyframe,
    before any resampling or roughening. `resampled` reports whether a
    resample was triggered by this keyframe's ESS, i.e. it acts on the state
    carried into the next keyframe.
    """
    keyframe_idx: int
    ess: float
    resampled: bool
    mean_east_m: float
    mean_north_m: float
    mean_heading_deg: float
    map_east_m: float
    map_north_m: float
    map_heading_deg: float
    position_std_m: float
    heading_std_deg: float
    n_measurements: int
    # Weight held by particles that came from some proposal event; 0 when
    # the belief is entirely motion-model descended.
    proposal_weight_share: float = 0.0
    proposal_event_id: int | None = None  # set on keyframes that fired
    associations: list[AssociationPosterior] = []
    modes: list[ModeRecord] = []
    # Shannon entropy of the mode weights, in nats: 0 when the belief is
    # effectively unimodal, log(k) when k modes share the mass equally.
    mode_entropy_nats: float = 0.0


class ProposalEvent(msgspec.Struct):
    """A fired proposal, logged for the run's event index (§7.3).

    Carries the provenance every injected particle points back to, so the
    viewer can answer "where did this mode come from" (§5.5 [CONTRACT]).
    """
    event_id: int
    keyframe_idx: int
    trigger: str  # "init" | "null_share" | "ess_floor"
    n_hypotheses: int
    n_injected: int
    n_tracklets_considered: int
    n_combinations_examined: int
    n_combinations_skipped: int
    # Evidence gate (§5.5): a rejected event has n_injected 0 and
    # gate_passed False. Scores are window log-likelihoods in nats.
    gate_passed: bool = True
    gate_best_hypothesis_nats: float | None = None
    gate_reference_nats: float | None = None
    # Parallel to the hypothesis index recorded on each injected particle.
    hypothesis_tracklet_ids: list[list[str]] = []
    hypothesis_landmark_ids: list[list[str]] = []


class TruthPose(msgspec.Struct):
    """Ground-truth pose. On real datasets `heading_deg` is GPS course, not
    a measured heading — diagnostics only, the filter never reads it."""
    keyframe_idx: int
    east_m: float
    north_m: float
    heading_deg: float


class RunManifest(msgspec.Struct):
    """The run's own record: config echo, provenance, replay surface.

    Provenance fields are REQUIRED (schema 0.3). A run that cannot name its
    inputs is not reproducible, and every manifest on the previous disk had
    them as None — which is why they are no longer optional:
      - max_visible_range_m: the catalog visibility radius this run was
        built with. A replay that guesses it silently changes which
        positions the proposal thinks a landmark could be seen from.
      - export_dir: where the inputs came from. Synthetic runs record
        "synthetic:<scenario>" explicitly rather than omitting it.
      - git_commit / argv / created: who made this, how, when.
    """
    schema_version: str
    scenario_name: str
    anchor_lat_deg: float
    anchor_lon_deg: float
    n_keyframes: int
    filter_config: FilterConfig
    landmarks: list[LandmarkEntry]
    matcher_version: str
    max_visible_range_m: float
    export_dir: str
    git_commit: str
    argv: list[str]
    created: str
    particle_history_sha256: str = ""
    # Optional pointer to the tracklet payload (crops, matcher prompts) the
    # run log deliberately does not carry.
    sources_dir: str | None = None
