"""Typed messages and run-artifact records for bearing-only localization.

Configs and interface messages are tagged + frozen (MSGSPEC_STRUCT_OPTS);
per-keyframe log records are plain mutable Structs.

The CompatibilityTable is the matcher-seam contract (design doc §6).
TrackletMeasurement is the sparse information-epoch event of §5.3: one fused
nominal-forward-frame bearing per tracklet per epoch, anchored at a keyframe.

Angle contract: `bearing_forward_cw_deg` is clockwise-positive from the fixed,
human-approved nominal-forward axis and stored in **[0, 360)**.
`delta_yaw_cw_rad` is likewise clockwise-positive. This forward/left/CW-yaw
motion contract is not generic robotics SE(2), whose yaw is normally
counterclockwise-positive. Producers normalize serialized bearings with
`% 360`; consumers compare angles with the wrap helpers in
`farfield.geometry`, never by subtraction. Nothing upstream is north-aligned.
"""

import msgspec

from common.python.serialization import MSGSPEC_STRUCT_OPTS

# 0.7 plus the additive retrieval observation source (CLD-3): new record
# types and defaulted manifest fields only, so every existing 0.7 export and
# run directory still decodes. A shape-changing edit must bump this.
SCHEMA_VERSION = "0.7"


class LandmarkEntry(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """One known-position landmark with explicit positional uncertainty."""
    landmark_id: str
    lat_deg: float
    lon_deg: float
    type_key: str
    position_sigma_m: float
    # Complete anchor-relative convex-hull/linestring geometry. Point features
    # leave both arrays empty. The arrays are parallel and never truncated.
    hull_east_m: list[float] = []
    hull_north_m: list[float] = []



class CompatibilityEntry(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    landmark_id: str
    log_lr: float


class CompatibilityTable(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Matcher-seam output for one tracklet (design doc §6).

    Landmarks absent from `entries` score `default_log_lr`. The filter clips
    every log_lr to [clip_lo, clip_hi]; with an uncalibrated matcher the
    clips and the null hypothesis carry the safety burden.
    """
    tracklet_id: str
    matcher_version: str
    entries: list[CompatibilityEntry]
    default_log_lr: float
    clip_lo: float
    clip_hi: float
    status: str  # "fast" | "refined"


class TrackletMeasurement(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """One information epoch: a fused nominal-forward-frame bearing."""
    tracklet_id: str
    anchor_keyframe_idx: int
    bearing_forward_cw_deg: float  # CW from nominal forward, in [0, 360)
    kappa: float  # von Mises concentration of the fused bearing


class RetrievalMeasurement(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """One keyframe's retrieval observation: a pose-scored field (CLD-3).

    The dense (n_nodes, n_heading_bins) score field itself lives in the run's
    `retrieval_fields.npz` (see localization/retrieval.py — the artifact
    contract's one home); this record is the typed event that anchors field
    `field_idx` at a keyframe. At most one per keyframe: the crops of one
    panorama are already pooled into the field, so a second submission would
    double-count the same pixels (the retrieval analogue of the
    information-epoch rule).
    """
    keyframe_idx: int
    field_idx: int
    pano_id: str


class RetrievalConfig(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Score -> likelihood calibration for retrieval observations (§5.5).

    L(x) = (1 - outlier_epsilon) * softmax_temperature(S)(x)
           + outlier_epsilon / |X|

    Both parameters are selected on geographically disjoint validation
    regions and then frozen. `calibration_frozen` says whether that has
    happened: until it has, every consuming run is a diagnostic, not an
    evaluation, and drivers must refuse to present it otherwise.
    """
    temperature: float
    outlier_epsilon: float
    calibration_frozen: bool = False


class OdometryDelta(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Forward/left/CW-yaw increment ending at ``keyframe_idx`` (§5.2).

    Consumers rotate first, then translate in the updated forward frame:
    ``yaw_k = yaw_{k-1} + delta_yaw_cw_rad`` followed by
    ``position_k = position_{k-1} + R_cw(yaw_k) [forward_m, left_m]``.
    ``delta_yaw_cw_rad`` is required —
    a producer with no usable yaw signal for a step emits 0 with
    `sigma_yaw_rad` inflated to a random-walk budget. Translation noise is
    isotropic on purpose: cross-track uncertainty is generated by heading
    uncertainty when the filter rotates the increment through each particle's
    heading, so a separate cross-track sigma would double-count it.
    """
    keyframe_idx: int
    forward_m: float
    left_m: float
    delta_yaw_cw_rad: float
    sigma_m: float  # isotropic per-axis translation noise std
    sigma_yaw_rad: float


class GaussianInit(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Local prior: isotropic Gaussian position, uniform heading."""
    mean_east_m: float
    mean_north_m: float
    sigma_m: float


class UniformBoxInit(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Global prior: uniform position over a box, uniform heading."""
    east_min_m: float
    east_max_m: float
    north_min_m: float
    north_max_m: float


class ProposalConfig(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Mixture proposal for global init and recovery (design doc §5.5).

    Every resolved value is echoed into the run manifest.
    """
    enabled: bool = True
    # Fire on the first observable recent-bearing window so an uninformative
    # UniformBoxInit can be replaced by resected poses. An informative local
    # Gaussian prior is never subject to this initialization injection.
    on_init: bool = True
    # Kidnapped detection fires on the FRACTION of recent measurements that
    # were null-dominated, not on a consecutive run: a displaced belief
    # re-explains some bearings with wrong landmarks, so null share
    # alternates rather than pinning high. Healthy tracking sits near 0.
    null_share_threshold: float = 0.8
    null_share_window: int = 8
    null_share_min_fraction: float = 0.25
    # Fire when ESS stays below this fraction of n_particles for this many
    # consecutive keyframes — sustained collapse, not the single-keyframe
    # dip a diffuse prior takes on its first informative measurement.
    ess_floor_frac: float = 0.02
    ess_floor_keyframes: int = 3
    # Minimum keyframes between events; recovery needs time to take hold.
    refractory_keyframes: int = 10

    # Hypothesis generation. Every table entry better than its default is a
    # candidate; computation is bounded by the particle budget rather than by
    # truncating a candidate list or a tied hypothesis list.
    max_tracklets: int = 5
    # Small Cartesian spaces are enumerated exactly. Large spaces receive a
    # deterministic systematic sample sized from the number of pose solutions
    # the injected particle budget can support.
    exhaustive_tuple_limit: int = 256
    tuple_samples_per_active_solution: int = 8
    # Minimum density around an activated solution when the kind's particle
    # share is large enough. With a smaller total budget, one solution receives
    # the available samples rather than violating the exact-count invariant.
    min_particles_point_fix: int = 32
    min_particles_arc: int = 64
    min_particles_single: int = 128
    # Near-identical solutions share one activation budget. Greedy selection
    # then balances compatibility evidence with pose-space diversity.
    solution_cluster_position_m: float = 75.0
    solution_cluster_heading_deg: float = 8.0
    pose_diversity_weight: float = 0.25
    # Long arcs need more samples to maintain comparable linear density.
    arc_length_reference_m: float = 1000.0
    arc_length_weight_cap: float = 10.0
    # Resection residual tolerance, in standard deviations of the bearing
    # measurement. It MUST scale with sigma — the residual of a true fix
    # grows with bearing noise, so a fixed ceiling rejects real solutions.
    residual_tolerance_sigma: float = 3.0
    max_residual_tolerance_deg: float = 90.0
    # Bearings within this many keyframes of the trigger are treated as
    # simultaneous (staggered epochs rarely put two bearings on one
    # keyframe; the induced angular error is under the bearing noise).
    window_keyframes: int = 4

    # Evidence gate on injection (§5.5): a fired trigger may displace belief
    # mass only when the proposal's best hypothesis explains the recent
    # bearing window better than every existing mode does, by this margin.
    # With no modes to protect (global init, modes disabled) the gate passes.
    evidence_gate: bool = True
    evidence_gate_margin_nats: float = 1.0
    # Charge log(n_hypotheses) for choosing the best of N hypotheses that
    # were each constructed to explain the very window they are scored on —
    # a multiple-comparisons correction that keeps the gate comparable as the
    # number of generated hypotheses changes.
    evidence_gate_selection_charge: bool = True
    # OBSERVABILITY, not a tuning knob: a pose is three unknowns and one
    # bearing is one equation, so an injection resected from fewer than
    # three tracklets is a smear masquerading as a fix. Applied to the INIT
    # trigger only — a recovery injection is rescuing a failing belief,
    # where a broad-but-containing family beats a confident wrong point.
    min_tracklets_for_injection: int = 3
    # ... but not forever: a sparse leg may never show three at once, and
    # firing late beats brute-forcing a region-sized uniform box.
    init_max_wait_keyframes: int = 40
    # Poses sampled per hypothesis when scoring it against the window.
    evidence_gate_samples: int = 16

    # How injected mass is split across hypothesis kinds (renormalized over
    # the kinds actually generated). Triples are sharp but few; singles are
    # broad but always available and still collapse the heading axis.
    share_triple: float = 0.5
    share_pair: float = 0.35
    share_single: float = 0.15

    # Fraction of particle mass replaced by proposed poses. The value controls
    # the tradeoff between retaining the incumbent and representing alternatives.
    inject_fraction: float = 0.5
    # FLOOR on the injected spread, not the spread itself: each hypothesis
    # carries its own spread (~sigma_bearing * range), and this only bounds
    # it below so a coarse fix is stated at the precision it actually has.
    injection_sigma_m: float = 100.0
    injection_heading_sigma_deg: float = 3.0
    # Ceiling, so one hopeless bearing cannot smear particles region-wide.
    max_injection_sigma_m: float = 2000.0


class ModeConfig(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    """Belief clustering for mode tracking (design doc §5.1/§5.6)."""
    enabled: bool = True
    cell_size_m: float = 150.0
    heading_cell_deg: float = 20.0
    # Cells lighter than this are noise, not part of any mode.
    min_cell_weight: float = 1e-4
    # A cluster must hold this much posterior mass to be called a mode.
    min_mode_weight: float = 0.02


class FilterConfig(msgspec.Struct, **MSGSPEC_STRUCT_OPTS):
    n_particles: int
    seed: int
    init: GaussianInit | UniformBoxInit
    # Per-tracklet null-hypothesis probability. With an uncalibrated matcher,
    # the null prevents incidental clutter alignments from forcing an identity.
    pi0: float = 0.2
    ess_resample_frac: float = 0.5
    # Heading random-walk noise per keyframe, in quadrature with each
    # increment's sigma_yaw_rad, covers yaw drift not declared by the producer.
    heading_random_walk_deg: float = 1.0
    # Kernel bandwidth for regularized resampling, as a multiple of the
    # Silverman-style rule sigma * n^(-1/6). Required for consistency: at 0
    # the resampled cloud collapses to duplicated atoms and the filter
    # reports a spread it no longer represents.
    resample_regularization: float = 1.0
    # Absolute jitter floors added on top of the kernel bandwidth, for
    # beliefs too collapsed for a proportional bandwidth to recover.
    position_roughening_m: float = 0.0
    heading_roughening_deg: float = 0.0
    # Bin size for the highest-density (MAP) position estimate.
    map_cell_size_m: float = 50.0
    checkpoint_every: int = 10
    # "numpy" (reference, bit-stable, CPU) or "torch" (GPU, float32; same
    # mixture, reductions differ at fp32 epsilon). Recorded so the manifest
    # states which engine produced a run.
    measurement_backend: str = "numpy"
    # §5.3 association persistence: a tracklet is ONE physical object, so
    # its identity persists across its epochs under a renewal HMM.
    # Marginalizing independently per epoch re-pays the 1/|catalog|
    # candidate prior on EVERY epoch, coupling bearing evidence to catalog
    # size; persistence pays it once per tracklet.
    association_persistence: bool = True
    # beta: per-epoch probability the tracklet's physical identity switched
    # (track swaps at occlusions are tracker behavior, not map behavior).
    association_renewal_rate: float = 0.1
    # eps: outlier rate within a correct association — a committed tracklet
    # can still emit a bad bearing (partial occlusion, panorama seam).
    association_outlier_rate: float = 0.1
    # Probability the true landmark appears among a table's endorsed entries
    # (given any exist), used to split a proper identity posterior between
    # endorsed and unendorsed candidates.
    matcher_recall: float = 0.5
    # Responsibilities below this are dropped from reported association
    # posteriors (likelihoods are never truncated), bounding dense-catalog
    # run time and artifact size.
    min_reported_responsibility: float = 1e-6
    # Survival floor for resampling (0 disables, the historical behavior):
    # every mode and proposal-cluster group whose posterior mass is at least
    # `resample_survival_min_mass` keeps at least this many offspring, which
    # then carry their group's TRUE mass (log_weight = log(mass/count)) so
    # the posterior is unchanged — representation is guaranteed, probability
    # is not. Resampling is a representational step; a hypothesis may die of
    # evidence (mass below the min) but not of sampling noise. Motivated by
    # the mount_washington leg3 seed study, where the correct init lineage
    # survived to a 61-particle remnant in converging seeds and went extinct
    # in the others — see docs/farfield/decisions.md, 2026-08-27.
    resample_survival_floor: int = 0
    # Mass below which a group is genuinely refuted and allowed to die.
    resample_survival_min_mass: float = 1e-9
    proposal: ProposalConfig = msgspec.field(default_factory=ProposalConfig)
    modes: ModeConfig = msgspec.field(default_factory=ModeConfig)
    # Present iff the run consumes retrieval score fields; the calibration
    # is part of the filter's model and therefore lives in its config echo.
    retrieval: RetrievalConfig | None = None


class ModeRecord(msgspec.Struct):
    """One mode at one keyframe."""
    mode_id: int
    weight: float
    n_particles: int
    mean_east_m: float
    mean_north_m: float
    mean_heading_deg: float
    position_std_m: float
    heading_std_deg: float
    birth_keyframe_idx: int
    parent_mode_ids: list[int] = []
    # Where this mode came from: motion-model descent, or a proposal event
    # with the tracklets/landmarks that generated it (§5.5 [CONTRACT]).
    provenance: dict[str, str | int] = {}


class ModeEvent(msgspec.Struct):
    """Birth, death or merge — the §7.3 auto-bookmarks for mode bookkeeping."""
    keyframe_idx: int
    kind: str  # "birth" | "death" | "merge"
    mode_id: int
    parent_mode_ids: list[int] = []
    detail: dict[str, str | int] = {}


class AssociationPosterior(msgspec.Struct):
    """Per-measurement association responsibilities (design doc §5.4).

    [CONTRACT] Reported PER MODE (`mode_id` set), not only averaged over the
    whole belief: for a multimodal posterior the global average blends two
    contradictory explanations into a number describing neither. The
    whole-belief average is still emitted, with mode_id None.
    """
    tracklet_id: str
    anchor_keyframe_idx: int
    null_share: float
    responsibilities: dict[str, float] = {}
    mode_id: int | None = None
    # Share of the group's mass explaining this tracklet through a
    # candidate the matcher does NOT vouch for: identity surprise. A
    # displaced belief re-explains bearings with wrong landmarks — cheaply
    # visible here, invisible to null share (§8.4).
    surprise_share: float = 0.0


class PositionMassMetricConfig(msgspec.Struct, frozen=True,
                               forbid_unknown_fields=True):
    """Identity and resolved radii for the primary truth-aware run metric."""
    metric_id: str
    metric_version: str
    radii_m: list[float]


class BearingResidualDiagnostic(msgspec.Struct, frozen=True,
                                forbid_unknown_fields=True):
    """One explicitly posterior-predictive bearing-model diagnostic."""
    keyframe_idx: int
    tracklet_id: str
    mode_id: int | None
    pose_east_m: float
    pose_north_m: float
    pose_heading_cw_deg: float
    null_share: float
    null_dominated: bool
    landmark_id: str | None
    association_probability: float | None
    signed_residual_deg: float | None

class HealthRecord(msgspec.Struct):
    """Tier-0 health scalars, one per keyframe (design doc §5.6/§7.1).

    All belief statistics describe the WEIGHTED posterior at this keyframe,
    before any resampling or roughening. `resampled` reports whether a
    resample was triggered by this keyframe's ESS, i.e. it acts on the state
    carried into the next keyframe.
    """
    keyframe_idx: int
    ess: float
    resampled: bool
    mean_east_m: float
    mean_north_m: float
    mean_heading_deg: float
    map_east_m: float
    map_north_m: float
    map_heading_deg: float
    position_std_m: float
    heading_std_deg: float
    n_measurements: int
    # Weight held by particles that came from some proposal event; 0 when
    # the belief is entirely motion-model descended.
    proposal_weight_share: float = 0.0
    proposal_event_id: int | None = None  # set on keyframes that fired
    associations: list[AssociationPosterior] = []
    modes: list[ModeRecord] = []
    # Shannon entropy of the mode weights, in nats: 0 when the belief is
    # effectively unimodal, log(k) when k modes share the mass equally.
    mode_entropy_nats: float = 0.0
    # Fully keyed posterior masses centered on the true position, from
    # RunManifest.position_mass_metric. Populated by the evaluation-only
    # observer at every keyframe when truth is available; empty otherwise.
    position_probability_mass: dict[str, float] = {}


class ProposalEvent(msgspec.Struct):
    """A fired proposal, logged for the run's event index (§7.3).

    Carries the provenance every injected particle points back to, so the
    viewer can answer "where did this mode come from" (§5.5 [CONTRACT]).
    """
    event_id: int
    keyframe_idx: int
    trigger: str  # "init" | "null_share" | "ess_floor"
    n_hypotheses: int
    n_injected: int
    n_tracklets_considered: int
    n_combinations_examined: int
    n_combinations_skipped: int
    particle_budget: int = 0
    n_combinations_total: int = 0
    n_combinations_enumerated: int = 0
    n_combinations_sampled: int = 0
    n_combinations_geometry_pruned: int = 0
    n_partially_represented_ties: int = 0
    n_solution_clusters_merged: int = 0
    represented_compatibility_mass: float = 0.0
    # Evidence gate (§5.5): a rejected event has n_injected 0 and
    # gate_passed False. Scores are window log-likelihoods in nats.
    gate_passed: bool = True
    gate_best_hypothesis_nats: float | None = None
    gate_reference_nats: float | None = None
    # Parallel to the hypothesis index recorded on each injected particle.
    hypothesis_tracklet_ids: list[list[str]] = []
    hypothesis_landmark_ids: list[list[str]] = []


class TruthPose(msgspec.Struct):
    """Ground-truth position plus recorded GPS/trajectory course.

    Course is diagnostic truth only. It is not a measured platform heading
    or fixed nominal-forward orientation, and the filter never reads it.
    """
    keyframe_idx: int
    east_m: float
    north_m: float
    course_world_cw_deg: float


class RunManifest(msgspec.Struct):
    """The run's own record: config echo, provenance, replay surface.

    Required provenance includes:
      - max_visible_range_m: the catalog visibility radius this run was
        built with, which shapes proposal hypotheses;
      - export_dir: where the inputs came from. Synthetic runs record
        "synthetic:<scenario>" explicitly;
      - git_commit / argv / created: who made this, how, when.
    """
    schema_version: str
    dataset: str
    scenario_name: str
    run_kind: str
    initialization_kind: str
    bearings_consumed: bool
    proposal_enabled: bool
    localization_inputs_manifest_sha256: str | None
    anchor_lat_deg: float
    anchor_lon_deg: float
    n_keyframes: int
    filter_config: FilterConfig
    landmarks: list[LandmarkEntry]
    matcher_version: str
    max_visible_range_m: float
    export_dir: str
    git_commit: str
    argv: list[str]
    created: str
    particle_history_sha256: str = ""
    # Explicit control classification. These tags identify ablations without
    # overloading matcher_version, which must continue to identify table bytes.
    ablation_tags: list[str] = []
    # Truth is optional. When present, schema identifies truth.jsonl and the
    # optional artifact mapping identifies its immutable external source.
    truth_position_artifact: dict[str, str] | None = None
    truth_position_schema: str | None = None
    # Resolved truth-centered primary-metric identity/config. None when no
    # truth is present. The default headline radius is 500 m.
    position_mass_metric: PositionMassMetricConfig | None = None
    # Retrieval observation source (schema 0.8): consumed iff the run's
    # filter multiplied retrieval score fields into the belief; the source
    # directory names where the fields came from. The consumed fields are
    # copied into the run artifact as replay surface.
    retrieval_consumed: bool = False
    retrieval_dir: str | None = None
