
cc_test(
  name = "openstreetmap_test",
  srcs = ["openstreetmap_test.cc"],
  data = ["@openstreetmap_snippet//:files"],
  deps = [
    "@fmt",
    "@libosmium",
    "@com_google_googletest//:gtest_main",
  ]
)
