
cc_library(
  name="argument_wrapper",
  hdrs=["argument_wrapper.hh"],
  visibility=["//visibility:public"],
)

cc_test(
  name = "argument_wrapper_test",
  srcs = ["argument_wrapper_test.cc"],
  deps = [
    ":argument_wrapper",
    "@com_google_googletest//:gtest_main",
  ]
)