import math
import unittest

from experimental.overhead_matching.swag.landmark_filtering.object_tracking import (
    mount_offset_sweep as mos,
)


def synthetic_tracklets(true_offset_deg, landmarks, n_obs=6, leg_m=400.0):
    """Observations of static landmarks from a boat running due north.

    Camera bearings are generated by inverting the relation the sweep solves,
    `bearing_world = course + bearing_camera - offset`, so the sweep should
    recover `true_offset_deg` exactly on noise-free input.
    """
    course = 0.0  # heading north; ENU north is +y
    by_tracklet = {}
    for i, (east, north) in enumerate(landmarks):
        observations = []
        for k in range(n_obs):
            boat_north = k * (leg_m / max(n_obs - 1, 1))
            bearing_world = math.degrees(
                math.atan2(east - 0.0, north - boat_north)) % 360.0
            camera = (bearing_world - course + true_offset_deg) % 360.0
            observations.append((0.0, boat_north, camera, course, k))
        by_tracklet[f"LT{i}"] = observations
    return by_tracklet


class ResidualTest(unittest.TestCase):

    def test_true_offset_gives_near_zero_residual(self):
        tracklets = synthetic_tracklets(
            214.0, [(300.0, 600.0), (-250.0, 500.0), (400.0, 900.0)])
        residual, n = mos.residual_at(214.0, tracklets, max_condition=1e9)
        self.assertEqual(n, 3)
        self.assertLess(residual, 1e-6)

    def test_wrong_offset_gives_large_residual(self):
        tracklets = synthetic_tracklets(
            214.0, [(300.0, 600.0), (-250.0, 500.0), (400.0, 900.0)])
        residual, _ = mos.residual_at(180.0, tracklets, max_condition=1e9)
        self.assertGreater(residual, 1.0)

    def test_sweep_recovers_the_true_offset(self):
        tracklets = synthetic_tracklets(
            214.0, [(300.0, 600.0), (-250.0, 500.0), (400.0, 900.0),
                    (150.0, 250.0)])
        curve = mos.sweep(tracklets, 1e9, 0.0, 360.0, 2.0)
        best = min(curve, key=lambda c: c[1])
        self.assertAlmostEqual(best[0], 214.0, delta=2.0)

    def test_condition_gate_drops_glancing_geometry(self):
        # A landmark 2 km ahead of a 400 m run is seen along almost one bearing,
        # so its rays intersect at a glancing angle: condition ~5.5e4. The
        # residual is still ~0, which is the whole point of gating on both --
        # the position is uncertain by kilometres along the line of sight.
        ahead = synthetic_tracklets(0.0, [(100.0, 2000.0)])
        residual, n_loose = mos.residual_at(0.0, ahead, max_condition=1e9)
        self.assertEqual(n_loose, 1)
        self.assertLess(residual, 1e-6)
        _, n_tight = mos.residual_at(0.0, ahead, max_condition=500.0)
        self.assertEqual(n_tight, 0)


class SupportGateTest(unittest.TestCase):
    """The gate that stops a candidate from winning by discarding data."""

    def test_floor_is_a_fraction_of_the_best_supported_candidate(self):
        curve = [(0.0, 5.0, 40), (5.0, 4.0, 20), (10.0, 3.0, 10)]
        kept, floor = mos.eligible(curve, 0.5)
        self.assertEqual(floor, 20)
        self.assertEqual([c[0] for c in kept], [0.0, 5.0])

    def test_excludes_the_leg1_style_low_support_spike(self):
        # The real failure: a 5-tracklet candidate edging out a 37-tracklet one.
        curve = [(85.0, 1.04, 5), (210.0, 1.05, 37), (300.0, 7.0, 31)]
        kept, _ = mos.eligible(curve, 0.5)
        self.assertNotIn(85.0, [c[0] for c in kept])
        self.assertAlmostEqual(min(kept, key=lambda c: c[1])[0], 210.0)

    def test_frac_zero_admits_everything(self):
        curve = [(85.0, 1.04, 5), (210.0, 1.05, 37)]
        kept, floor = mos.eligible(curve, 0.0)
        self.assertEqual(floor, 1)
        self.assertEqual(len(kept), 2)

    def test_empty_curve_is_handled(self):
        self.assertEqual(mos.eligible([], 0.5), ([], 0))


class AssessTest(unittest.TestCase):

    def test_deep_single_basin_is_unimodal(self):
        # Smooth V with a clear floor.
        curve = [(float(a), 1.0 + abs(a - 200) * 0.1, 30)
                 for a in range(0, 360, 10)]
        verdict, _, ok = mos.assess(curve, min(r for _, r, _ in curve), n_used=30)
        self.assertEqual(verdict, "SMOOTH UNIMODAL")
        self.assertTrue(ok)

    def test_flat_curve_is_rejected(self):
        curve = [(float(a), 4.0 + 0.01 * (a % 3), 30)
                 for a in range(0, 360, 10)]
        verdict, detail, ok = mos.assess(curve, min(r for _, r, _ in curve), n_used=30)
        self.assertEqual(verdict, "FLAT")
        self.assertFalse(ok)
        self.assertIn("noise", detail)

    def test_two_equal_basins_are_rejected(self):
        curve = []
        for a in range(0, 360, 10):
            d = min(abs(a - 90), abs(a - 270))
            curve.append((float(a), 1.0 + d * 0.1, 30))
        verdict, detail, ok = mos.assess(curve, min(r for _, r, _ in curve), n_used=30)
        self.assertEqual(verdict, "MULTIMODAL")
        self.assertFalse(ok)
        self.assertIn("90", detail)
        self.assertIn("270", detail)

    def test_a_basin_sampled_twice_is_one_basin(self):
        # Two adjacent grid points tie at the floor: still one minimum.
        curve = [(0.0, 5.0, 30), (10.0, 1.0, 30), (20.0, 1.0, 30),
                 (30.0, 5.0, 30), (40.0, 6.0, 30), (50.0, 7.0, 30)]
        verdict, _, ok = mos.assess(curve, 1.0, n_used=30)
        self.assertEqual(verdict, "SMOOTH UNIMODAL")
        self.assertTrue(ok)


class UnderSupportTest(unittest.TestCase):

    def test_one_tracklet_is_refused_however_clean_the_curve(self):
        # mount_washington_20260815_leg1 shape: a single tracklet traces a
        # perfectly smooth bowl, and every relative gate passes it.
        curve = [(float(o), 1.0 + abs(o - 210) / 40.0, 1)
                 for o in range(0, 360, 5)]
        verdict, detail, ok = mos.assess(curve, min(r for _, r, _ in curve),
                                         n_used=1)
        self.assertEqual(verdict, "UNDER-SUPPORTED")
        self.assertFalse(ok)
        self.assertIn("1 well-conditioned tracklet", detail)

    def test_the_floor_is_adjustable(self):
        curve = [(float(o), 1.0 + abs(o - 210) / 40.0, 3)
                 for o in range(0, 360, 5)]
        _, _, ok = mos.assess(curve, min(r for _, r, _ in curve), n_used=3,
                              min_tracklets=2)
        self.assertTrue(ok)

if __name__ == "__main__":
    unittest.main()


class ArcGateTest(unittest.TestCase):
    """The arc gate's defining property is that the candidate offset cannot
    change it -- that is what makes the tracklet set fixed across a sweep."""

    def observations(self, bearings, course=0.0):
        # (east, north, camera, course, keyframe)
        return [(float(i) * 100.0, 0.0, b, course, i)
                for i, b in enumerate(bearings)]

    def test_arc_is_the_smallest_containing_span(self):
        self.assertAlmostEqual(
            mos.arc_deg(self.observations([10.0, 30.0, 50.0])), 40.0, places=6)

    def test_arc_wraps_around_north(self):
        # 350, 0, 10 spans 20 deg, not 350.
        self.assertAlmostEqual(
            mos.arc_deg(self.observations([350.0, 0.0, 10.0])), 20.0, places=6)

    def test_arc_is_invariant_to_the_candidate_offset(self):
        # The whole justification for gating on arc rather than on condition.
        base = [12.0, 47.0, 88.0, 300.0]
        reference = mos.arc_deg(self.observations(base))
        for offset in (0.0, 37.0, 123.5, 214.0, 359.0):
            rotated = [(b - offset) % 360.0 for b in base]
            self.assertAlmostEqual(mos.arc_deg(self.observations(rotated)),
                                   reference, places=6,
                                   msg=f"arc moved at offset {offset}")

    def test_course_variation_counts_toward_the_arc(self):
        # A tracklet held at a constant camera bearing while the vehicle turns
        # still sweeps the world bearing, and that is what triangulation uses.
        obs = [(0.0, 0.0, 100.0, 0.0, 0), (100.0, 0.0, 100.0, 40.0, 1),
               (200.0, 0.0, 100.0, 80.0, 2)]
        self.assertAlmostEqual(mos.arc_deg(obs), 80.0, places=6)

    def test_single_observation_has_no_arc(self):
        self.assertEqual(mos.arc_deg(self.observations([10.0])), 0.0)
