FROM nvidia/cuda:12.8.1-devel-ubuntu24.04

ARG USERNAME=runner
ARG USER_UID=1001
ARG USER_GID=$USER_UID

RUN apt-get update && apt-get -y install curl vim libicu-dev git sudo lsb-release git-lfs python3 python-is-python3 jq
RUN mkdir /actions-runner && \
        cd /actions-runner && \
        curl -o actions-runner-linux-x64-2.323.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.323.0/actions-runner-linux-x64-2.323.0.tar.gz && \
        echo "0dbc9bf5a58620fc52cb6cc0448abcca964a8d74b5f39773b7afcad9ab691e19  actions-runner-linux-x64-2.323.0.tar.gz" | shasum -a 256 -c && \
        tar -xzf ./actions-runner-linux-x64-2.323.0.tar.gz && \
        groupadd --gid $USER_GID $USERNAME && \
        useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
        usermod -aG sudo $USERNAME && \
        curl -o /usr/bin/bazel -L https://github.com/bazelbuild/bazelisk/releases/download/v1.25.0/bazelisk-linux-amd64 && \
        chmod a+x /usr/bin/bazel && \
        git lfs install
RUN echo "$USERNAME ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/$USERNAME
RUN mkdir -p "/home/$USERNAME/.local/bin"
COPY launch.sh /actions-runner

WORKDIR /actions-runner
USER $USERNAME
