name: github_runner

services:
  github_runner:
    container_name: github_runner
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: github_runner:24.04
    shm_size: 2gb
    runtime: nvidia
    command: bash -c "./config.sh --url https://github.com/ewfuentes/robot --token ${GITHUB_RUNNER_TOKEN} --unattended && ./run.sh"
    restart: always
