name: github_runner

services:
  github_runner:
    container_name: github_runner
    image: github_runner:24.04
    shm_size: 2gb
    runtime: nvidia
    command: bash -c "./config.sh --url https://github.com/ewfuentes/robot --token ${GITHUB_RUNNER_TOKEN} --unattended && ./run.sh"
    restart: always
    volumes:
      - /data/docker_ci_cache:/tmp/caches
