# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '00 23 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checking out  ${{ github.sha }}
        uses: actions/checkout@v3

      - name: Lint C++ Files
        run: |
          shopt -s globstar
          clang-format --dry-run --Werror **/*.cc **/*.hh

  unit-test:
    continue-on-error: true
    strategy:
      matrix:
        build-config: [gcc, clang]
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    env:
      cache_secret_file: cache_auth.json
      cache_url: https://storage.googleapis.com/robot-research-bazel-cache
      cache_auth: ${{ secrets.BAZEL_CACHE_BASE64 }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Fetch Secrets
        run: |
          echo ${{ env.cache_auth }} | base64 --decode > ${{ runner.temp }}/${{ env.cache_secret_file }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checking out  ${{ github.sha }}
        uses: actions/checkout@v3
        with:
          lfs: true

      # Runs a set of commands using the runners shell
      - name: Setup Dependencies
        run: |
          ./setup.sh

      - name: Run Unit Tests
        run: |
          bazel test --config=${{ matrix.build-config }} --remote_cache=${{ env.cache_url }} --google_credentials=${{ runner.temp }}/${{ env.cache_secret_file }} //... --test_output=errors --test_timeout_filters=-eternal
